name: Deploy
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: Hugo-Carvalho/vitibrasil_api
          token: ${{ secrets.DEPLOY }}
          path: vitibrasil_api
      - name: Run script file
        run: |
           ls vitibrasil_api
        shell: bash
