name: Deploy
on: push
env:

  TF_LOG: INFO
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE}}
  GT_TOKEN: ${{ secrets.DEPLOY }}

  
jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./vitibrasil_api-blueprints
 
    steps:
      - name: Git Clone Repo APP
        uses: actions/checkout@v4
        with:
          repository: Hugo-Carvalho/vitibrasil_api
          token: ${{env.GT_TOKEN}}
          path: vitibrasil_api

      - name: Git Clone Repo APP
        uses: actions/checkout@v4
        
      - name: Running terraform
        uses: hashicorp/setup-terraform@v3
  
      - name: Terraform init
        id: init
        run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"

      - name: Terraform plan
        id: plan
        run: terraform plan
        continue-on-error: true

