name: Deploy
on:
  repository_dispatch:
    types: [trigger-workflow]

env:

  TF_LOG: INFO
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  REGION: ${{ secrets.AWS_REGION }}
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE}}
  GT_TOKEN: ${{ secrets.DEPLOY }}

  
jobs:
  terraform:
    runs-on: ubuntu-latest
 
    steps:
      - name: teste
        run: ls ${{env.GT_TOKEN}}