name: Deploy

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Responda com (y/n), você tem certeza que deseja destruir os serviços em PRD?'
        required: true

env:

  TF_LOG: INFO
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  REGION: ${{ secrets.AWS_REGION }}
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE}}
  GT_TOKEN: ${{ secrets.DEPLOY }}

  
jobs:
  terraform:
    runs-on: ubuntu-latest
 
    steps:
      - name: teste
        run: ls ${{env.GT_TOKEN}}